### PR TITLE
Changing select index error message to be more informative (#173)

### LINKED ISSUE #173: [Good first issue] Update message shown when a single index is selected in search comparison tool
### What is the bug?
When the search button is pressed and a single search is performed, an error message appears saying "An index is required. Select an index."

Screen Shot 2023-04-13 at 8 31 07 AM

### How can one reproduce the bug?
1. Select index on either left or right hand side
2. Click search button

### What is the expected behavior?
Three possibilities:
1. If a single search is not permitted, display an error message but do not execute the search.
2. If a single search is permitted, delete the error message.
3. If a single search is permitted, change the font color to black and display a recommendation wording such as "try comparing search results by selecting an index."

### Do you have any additional context?
I would want to clarify the expected behavior.

### PR DESCRIPTION
**Pull request by evankielley**
### Description
When a user submits a search query with no index or only one index selected, an error message is displayed that tells the user to select an index. This pull request changes that error message to be more informative.

### Issues Resolved
Resolves #173 

#### Before

(Before) Both left and right indices selected
before-both-selected

(Before) Only left index selected
before-left-selected

(Before) Only right index selected
before-right-selected

(Before) Neither left nor right indices selected
before-none-selected

#### After

(After) Both left and right indices selected
after-both-selected

(After) Only left index selected
after-left-selected

(After) Only right index selected
after-right-selected

(After) Neither left nor right indices selected
after-none-selected

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by evankielley** [comment]
> @evankielley Thank you for your contribution to the DSR plugin! Could please add a screenshot of the page before and after the changes. Also, the identical error message appears in multiple files; can we make it a constant? Please disregard the yarn.lock file change. The maintainers are addressing it now.

No problem, will do!

**Comment by evankielley** [comment]
Ready for re-review

**Review by noCharger — APPROVED** [review]
The change looks good to me. Can you rebase it since the yarn.lock fix should resolved https://github.com/opensearch-project/dashboards-search-relevance/pull/271

**Comment by evankielley** [comment]
> The change looks good to me. Can you rebase it since the yarn.lock fix should resolved #271

Oh nice. Will do. Sorry I forgot that earlier.

**Comment by evankielley** [comment]
Ready

**Comment by noCharger** [comment]
https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/6090046855/job/16524884733?pr=270

```
| Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-amazon-kendra-intelligent-ranking-3.0.0.0 due to jar hell
| 	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:681)
| 	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:862)
| 	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:830)
| 	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:276)
| 	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)
| 	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
| 	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
| 	at org.opensearch.cli.Command.main(Command.java:101)
| 	at org.opensearch.plugins.PluginCli.main(PluginCli.java:[66](https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/6090046855/job/16524884733?pr=270#step:7:67))
| Caused by: java.lang.IllegalStateException: jar hell!
| class: org.apache.commons.logging.impl.AvalonLogger
| jar1: /home/runner/work/dashboards-search-relevance/dashboards-search-relevance/search-processor/amazon-kendra-intelligent-ranking/build/testclusters/integTest-0/distro/3.0.0-ARCHIVE/plugins/.installing-1110415763305379888/commons-logging-1.2.jar
| jar2: /home/runner/work/dashboards-search-relevance/dashboards-search-relevance/search-processor/amazon-kendra-intelligent-ranking/build/testclusters/integTest-0/distro/3.0.0-ARCHIVE/lib/commons-logging-1.2.jar
| 	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)
| 	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)
| 	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:[67](https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/6090046855/job/16524884733?pr=270#step:7:68)9)
| 	... 11 more

FAILURE: Build failed with an exception.
```

The jar hell [issue](https://github.com/opensearch-project/OpenSearch/pull/9779) should be resolved after the new artifacts for OpenSearch core are available. Merge this PR now.

**Pull request merged**
