### PR TITLE
Remove Cypress dependency

### PR DESCRIPTION
**Pull request by msfroh**
Cypress tests were moved to the opensearch-dashboards-functional-test repo.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by noCharger** [comment]
Related issue https://github.com/opensearch-project/dashboards-search-relevance/issues/266

**Review by macohen — APPROVED** [review]
So it looks like removing the cypress.json and cypress from package.json fixed the jarhell issue?

**Comment by noCharger** [comment]
Can we remove everything in `.cypress`?

**Review by noCharger — APPROVED** [review]

**Comment by noCharger** [comment]
@msfroh Needs manual backport.

```
https://github.com/opensearch-project/dashboards-search-relevance/actions/runs/6101854880/job/16559074799

  /usr/bin/git cherry-pick -x -n aa9b0630d527690e16f99da6320072a32bfef574
  Auto-merging package.json
  Auto-merging yarn.lock
  CONFLICT (content): Merge conflict in yarn.lock
  error: could not apply aa9b063... Remove Cypress dependency (#274)
  hint: after resolving the conflicts, mark the corrected paths
  hint: with 'git add <paths>' or 'git rm <paths>'
  Error: Possibly a conflict error. Trying to skip possible conflict files. 
```

**Comment by msfroh** [comment]
Manual backport: https://github.com/opensearch-project/dashboards-search-relevance/pull/277

**Pull request merged**
