### PR TITLE
Adding release notes for 2.11.0

### PR DESCRIPTION
**Pull request by harshavamsi**
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>

### Description
Adds release notes for the 2.11 release

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by harshavamsi** [comment]
https://github.com/opensearch-project/dashboards-search-relevance/pull/324/files?short_path=2aa4917#diff-2aa4917eeff089adcaab073bcf6bd08e9ad83480ccc31d1488077bf41ed09c10

**Comment by mingshl** [comment]
did these two PRs get into 2.11? if so, we need to add into 2.11 release note

https://github.com/opensearch-project/dashboards-search-relevance/pull/300
https://github.com/opensearch-project/dashboards-search-relevance/pull/314

**Comment by sejli** [comment]
The `2.11` branch was a cut a bit earlier than the first RC.  I believe these PRs may have gone in, if the RCs are cut from the `2.x` branch. May need to verify with the current RCs.

**Review by mingshl — APPROVED** [review]
the release notes LGTM. One to do item, probably should do before generating the release note, is to label the tickets accordingly based on the category. The [git-release-notes](https://github.com/ariatemplates/git-release-notes) should be able to auto generate the notes categorized the tickets based on the labels.

**Review by sejli — APPROVED** [review]

**Pull request merged**
